version: '3.8'
services:
  db:
    image: postgres:13
    ports:
      - '5438:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  cache:
    image: 'bitnami/redis:latest'
    ports:
      - '6380:6379'
    volumes:
      - ./cache:/data
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}